### ISSUE TITLE
USER STORY: Set up Superuser

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#1]
As an **Administrator** I can **login in and out of my superuser account** so that **I can manage the site**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Set up Django structure
- [x] Create superuser

**Acceptance Criteria**
- [x] Check Django site is running of local server
- [x] Login with superuser to admin account to check access
