### ISSUE TITLE
USER STORY: Country Selection

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#11]
As a **user** I can **select countries from a map or dropdown** so that **I can access information about them**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Create Diary app
- [x] Set url path
- [x] Import country json file
- [x] Create Country Model
- [x] Use json file to generate countries from Country model
- [x] Create map html page
- [x] Add SVG to map html page
- [x] Add MapView
- [x] Add Country Dropdown

**Acceptance Criteria:**

- [x] User can navigate to country page by selecting country on map
- [x] User can navigate country page by selecting dropdown on map 

**Unit Testing:**

- [x] Check URL resolves
- [x] Country Model
- [x] Map View
