### ISSUE TITLE
USER STORY: Country Info

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#12]
As a **user** I can **access basic country info** so that **I can decide if it is somewhere I might be interested in visiting**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Present visited stats onto map screen
- [x] Present country info on country specific html
- [x] Add flags to countries
- [x] Add picture to countries
- [x] Style map html
- [x] Style country html


**Acceptance Criteria:**

- [x]  User can see the percentage of countries they have visited on the map html.
- [x]  User can see basic stats about a country when they access the country specific page.
- [x]  User can see from the map drop-downs which countries they have visited

**Unit Testing:**

- [x]  Re-run unit test to check to new coverage gaps
