### ISSUE TITLE
USER STORY: Country Visited

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#13]
As a **user** I can **mark a country to visited** so that **I can see at a glance where I have been**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Set url path to country html
- [x] Create visited model
- [x] Create visited form
- [x] Create visited view - get function
- [x] Create visited view - post function
- [x] Pass visited model objects filtered to user id to  map to update css style
- [x] Use visited countries by user id to create ctx dict
- [x] Create country html

**Acceptance Criteria:**

- [x] User can go to country and mark to visited or wish list
- [x] User can see from the map which countries they have visited
- [x] User can see from the map map drop-downs which countries they have visited

**Unit Testing:**

- [x] Check URL resolves
- [x] Visited Model
- [x] Country View
