### ISSUE TITLE
USER STORY: Diary Linked To Country

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#14]
As a **user** I can **create a diary linked to a country I have visited** so that **I can record my experiences**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create url for viewing diary posts
- [x]  Create url for adding diary posts
- [x]  Create view for viewing diary posts using View
- [x]  Create view for adding diary posts using CreateView
- [x]  Add LoginMixin to diary view and diary add view
- [x]  Create model for diary with foreign keys to user and country and TaggitManager used for tags
- [x]  Create template for diary
- [x]  Create template for adding a diary post (diary_form)

**Acceptance Criteria:**

- [x]  Users will be able to add diary posts related to the country they are in including content, img, rating and tags
- [x]  Users will be able to access posts related to the country they are reviewing where they are the author
- [x]  Users will be able to search posts by content info, tags applied to posts and experience rating added to post
- [x]  Users will be able to view two posts per page

**Unit Testing:**

- [x]  diary urls
- [x]  diary views
- [x]  diary model
