### ISSUE TITLE
USER STORY: Delete Diary Posts

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#17]
As a **user** I can **delete diary posts** so that **I can remove unwanted information**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create url for diary delete confirmation
- [x]  Create view for diary delete using DeleteView
- [x]  Add LoginMixin to diary delete view
- [x]  Add UserPassesTestMixin to diary delete view
- [x]  Create delete confirmation template

**Acceptance Criteria:**

- [x]  Users will be able to delete posts related to the country they are reviewing where they are to author

**Unit Testing:**

- [x]  diary url
- [x]  diary view
