### ISSUE TITLE
USER STORY: Site Update Comments

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#19]
As a **user** I can **comment on site updates** so that **I can influence future site enhancements**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Create View for individual update posts
- [x] Create url for individual update posts
- [x] Create html for individual update posts 
- [x] Create UpdateComments model
- [x] Pass comments to view
- [x] Create comments form


**Acceptance Criteria:**

- [x] User can access a specific site update post and add comments to it.
- [x] User can view comments posted by themselves or other users 
- [x] Administrator can view comments posted by users
