### ISSUE TITLE
USER STORY: Admin add or delete user accounts

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#2]
As an **Administrator** I can **add or delete user accounts** so that **I can manage the site**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x]  Admin User tests to check functionality/ authorisation

**Acceptance Criteria**
- [x]  Create a user account from the admin page to test authorisation
- [x]  Delete user to test authorisation
