### ISSUE TITLE
USER STORY: Delete Site Update Comments

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#21]
As a **user** I can **delete my comments on site updates** so that **i can remove comments that are no longer relevant**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create URL for delete comments
- [x]  Create view for deleting comments
- [x]  Create html for for deleting comments

**Acceptance Criteria:**

- [x]  Users can delete comments posted by themselves.
- [x]  Users can view deleted comments posted by themselves and others.
- [x]  Administrator can view comments deleted by users

**Unit Testing:**

- [x]  comment delete url
- [x]  CommentDeleteView

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [ ]  Create URL for deleting comments
- [ ]  Create view for deleting comments
- [ ]  Create html for for deleting comments

**Acceptance Criteria:**

- [ ]  Users can delete comments posted by themselves.
- [ ]  Users can is given confirmation check before deletion.

**Unit Testing:**

- [ ]  comment delete url
- [ ]  CommentDeleteView
