### ISSUE TITLE
USER STORY: Login Restrictions

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#24]
As a **user** I can **restricted from specific site updates, map and countries without first logging in** so that **I can do not try to submit a comment or visited with no user to assign to the object and generate an error.**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Apply Login Required Mixin to restricted class views. 

**Acceptance Criteria:**

- [x]  User is redirected to login page when trying to access restricted pages
- [x]  User is automatically redirected the page they were attempting to access after successful login
