### ISSUE TITLE
USER STORY: Custom Restricted/Error Pages

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#26]
As a **user** I am **sent to an instructive page when I am unable to access a web page for any reason** so that **I understand why I am unable to access the page requested**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create 403 html
- [x]  Create 404 html
- [x]  Create 500 html
- [x] Create 400 html
- [x] Create 403 URL
- [x] Create 404 URL
- [x] Create 500 URL
- [x] Create 400 URL

**Acceptance Criteria:**

- [x]  User is sent to custom 403 page when attempting to access other users comments
- [x]  User is sent to custom 404 page when attempting to access unavailable page.
- [x]  User is sent to custom 500 page when page experiences server issue.
- [x] User is sent to custom 400 page for bad requests.
