### ISSUE TITLE
USER STORY: Create User Profile

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#28]
As a **user** I can **see my profile information** so that **i can confirm if it is correct**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create app for user_profile 
- [x]  Create url for profile
- [x]  Create view for profile
- [x]  Add LoginMixin to profile view
- [x]  Create template for profile
- [x]  Create model for profile with foreign key to user
- [x]  Create Signal to generate profile on registration of new user or if update profile if user info updated

**Acceptance Criteria:**

- [x]  Users will be able to view profile after registering an account
- [x]  Users will be able to view their username, email
- [x]  Users will have a default profile img and background profile img assigned to them on registration
- [x]  Users will have a space for travel objectives
- [x]  User will be able to view the wish list of countries they have created in the planner and access these countries directly from their profile

**Unit Testing:**

- [x]  profile url
- [x]  profile view
- [x]  profile model
