### ISSUE TITLE
USER STORY: Profile Update

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#29]
As a **user** I can **update my profile info** so that **it reflects any changes to my circumstances**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create url for profile updates
- [x]  Create form for profile updates
- [x]  Create view for profile updates
- [x]  Create template for profile updates

**Acceptance Criteria:**

- [x]  Users will be able to update their email, username, profile img, background img, travel objectives

**Unit Testing:**

- [x]  profile updates url
- [x]  profile updates view
