### ISSUE TITLE
USER STORY: Admin update user account information

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#3]
As an **Administrator** I can **update user account information** so that **I can assist users where required**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x]  Admin User tests to check functionality/ authorisation

**Acceptance Criteria:**
- [x]  As admin update user username to test authorisation
- [x]  As admin update user email to test authorisation
- [x]  As admin update user password to test authorisation
