### ISSUE TITLE
USER STORY: Diary Tags

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#30]
As a **user** I can **view a list of all the tags added to my diary posts related to the country I am in** so that **I can search via the tags**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create url for diary tags page
- [x]  Create view for diary tags using View
- [x]  Add LoginMixin to tags view
- [x]  Create tags template

**Acceptance Criteria:**

- [x]  Users will be able to view a list of all the tags added to their diary posts related to the country they are in so that they can search via the tags.

**Unit Testing:**

- [x]  diary tags url
- [x]  diary tags view
