### ISSUE TITLE
USER STORY: To-Do List View

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#32]
As a **user** I can **view all the to-do lists i have for a country** so that **i can plan and track my travel and holiday activities**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x] Create app for to-do lists
- [x] Create url for to-do lists
- [x] Create model for to-do lists - Foreign keys to User and Country
- [x] Create view for to-do lists (get function)
- [x] Create template for to-do lists

**Acceptance Criteria:**
- [x] Users will be able to see all to-do lists
- [x] Users will not be able to see to-do list description on the view page

**Unit Testing:**
- [x] Check URL resolves
- [x] To-Do List View (get function)
- [x] To-Do List Model
