### ISSUE TITLE
USER STORY: Delete To-Do Lists

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#34]
As a **user** I can **delete to-do lists** so that **I can remove lists that are no longer required**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create URL for delete to-do lists
- [x]  Create view for delete to-do lists
- [x]  Update to-do list template with delete button

**Acceptance Criteria:**

- [x]  Users will be able to delete to-do lists
- [x]  User will not receive a confirmation delete message due to the simple nature of the lists

**Unit Testing:**

 - [x] Check URL resolves
 - [x] To-Do Delete View
