### ISSUE TITLE
USER STORY: To-Do Items View

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#36]
As a **user** I can **view all items in a to-do list** so that **I can see what specific activities are required**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Create URL for viewing To-Do Items
- [x] Create To-Do Items model
- [x] Create view To-Do Items (get function)
- [x] Create To-Do Items template

**Acceptance Criteria:**

- [x]  Users will be able to view all To-Do Items in a list
- [x]  Updates will be ordered so completed items will appear last

**Unit Testing:**

- [x] Check URL resolves
- [x] To-Do Items View (get function)
- [x] To-Do Items Model
