### ISSUE TITLE
USER STORY: Add To-Do Items

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#37]
As a **user** I can **add new to-do items to a list** so that **I can manage new tasks i consider**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x] Update View for To-Do Items (post function)
- [x] Create To-Do Item form
- [x] Update To-Do Items template with form for inputs

**Acceptance Criteria:**

- [x] Users will be able to add new items in a list
- [x] Users will only be asked to input the item name

**Unit Testing:**

- [x] To-Do Items View (post function)
