### ISSUE TITLE
USER STORY: Toggle To-Do Items to Complete or Open

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#38]
As a **user** I can **toggle to-do items to open or closed** so that **I can see which tasks are outstanding**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create url for toggle complete To-Do Items
- [x]  Create view for toggle complete To-Do Items
- [x]  Update To-Do Item view template with toggle complete button

**Acceptance Criteria:**

- [x]  Users will be able to toggle items from open to closed
- [x]  Users will be able to toggle items from closed to open
- [x]  Closed items will move to the bottom of the page

**Unit Testing:**

- [x]  Check URL resolves
- [x] To-Do Toggle Complete View
