### ISSUE TITLE
USER STORY: Delete To-Do Items

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#39]
As a **user** I can **delete to-do items** so that **I can remove tasks that are no longer required**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**

- [x]  Create url for delete To-Do Items
- [x]  Create view for delete To-Do Items
- [x]  Update To-Do Items template with delete button

**Acceptance Criteria:**

- [x]  Users will be able to delete To-Do Items
- [x]  User will not receive a confirmation delete message due to the simple nature of the items

**Unit Testing:**

- [x]  Check URL resolves
- [x] To-Do Delete View
