### ISSUE TITLE
USER STORY:  User registration

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#4]
As a **user** I can **register an account** so that **I can log in with my password**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x] Create home app
- [x] Create base.html template with menu/footer
- [x] Create home-base.html template
- [x] Create register.html
- [x] Create UserRegister form class in forms.py file. Inherit UserCreationForm and add email
- [x] Link project url path to home-app url file
- [x] Create register url
- [x] Create register function in views
- [x] Style base.html
- [x] Style home-base.html
- [x] Style register.html

**Acceptance Criteria:**
- [x]  Register an account as a user
- [x]  Confirm the registration creates a user model

**Unit Testing:**
- [x] Check URL resolves
- [x] Register Views
- [x] Registration Form
