### ISSUE TITLE
USER STORY: User login

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#5]
As a **user** I can **login in and out of my account** so that **I can use the site**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x]  Create home.html
- [x]  Create path for login view using LoginView class from django_contrib.auth views - direct to login.html
- [x]  In settings set LOGIN_REDIRECT_URL = "travel-home"
- [x]  Create login.html
- [x]  Create path for logout view using LogoutView class from django_contrib.auth views - direct to home.html
- [x]  Redirect Register to login page on completion
- [x]  Style home.html
- [x]  Style login.html

**Acceptance Criteria:**
- [x]  Log in as a user using their registered account details
- [x]  Logout as a user

**Unit Testing:**
- [x]  Check URL resolves for home
- [x]  Check URL resolves for login
- [x]  Check URL resolves for logout
- [x]  Home View
- [x]  Login View

**Comment by Joe-Collins-1986** [comment]
Updated Register to login automatically with no requirement to redirect to login and enter details again.
