### ISSUE TITLE
USER STORY: User password reset

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#6]
As a **user** I can **reset my password** so that **I can still use the site if I have forgotten it or if it needs changing due to a security breach**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x]  Build password-reset url
- [x]  Build password-reset-confirm url
- [x]  Build password-reset-done url
- [x]  Build password-reset-complete url
- [x]  Build password-reset html template
- [x]  Build password-reset-confirm html template
- [x]  Build password-reset-done html template
- [x]  Build password-reset-complete html template
- [x]  Set up App Password on Google accounts for mail usage
- [x]  Add email settings to settings
- [x]  Add email password and host address to env file
- [x]  User testing

**Acceptance Criteria:**
- [x]  User can access password reset template
- [x]  User can enter email to receive password reset instructions
- [x]  User can receive email
- [x]  User can use email to to access password-reset-confirmation
- [x]  User directed back to login after reseting password
- [x]  User can log on with new password

**Unit Testing:**
- [x]  Check URL resolves for password_reset
- [x]  Check URL resolves for password_reset_confirm
- [x]  Check URL resolves for password_reset_done
- [x]  Check URL resolves for password_reset_complete

**Comment by Joe-Collins-1986** [comment]
Error when running locally - port 587 blocked.

- [x] confirm email sends when hosted on Heroku

**Comment by Joe-Collins-1986** [comment]
**NOTE:** BT internet are viewing email as spam and not letting through to user. 

This is acceptable as this is only a prototype, but if it was to launch live this would need to be addressed by contacting BT and working with them to allow the emails through.
