### ISSUE TITLE
USER STORY: Host site

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#7]
As a **Site Owner** I can **host the site on a cloud platform** so that **it can accessed by user be scaled up as appropriate**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x]  Create new Heroku  application
- [x]  Set up PostgressSQL Database via ElephantSQL
- [x]  Set up AWS account and set authorisation levels for static and media files
- [x]  Modify the settings.py to accommodate database, static/media files and email hosting
- [x]  Move os.environment variables from env file to Heroku config variables
- [x]  Set Heroku Debug to False
- [x]  Deploy site and link to GitHub for auto updates

**Acceptance Criteria:**
- [x]  User can access the site from link generated through Heroku
- [x]  html templates are all displaying correctly and linking as designed
- [x]  User can complete pre-built functionality - register, login, logout
- [x]  Check Database working - Admin can check that users are added to database
- [x]  Check AWS working - css styling and background image are showing
- [x]  Check Bootstrap is linked by checking Bootstrap styling and menu JS usage
- [x]  Confirm Heroku does not block port for password reset email and user can reset password
