### ISSUE TITLE
USER STORY: Admin site updates

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#8]
As an **Administrator** I can **post site updates** so that **users can be informed about latest features/updates**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x] Build topics model - topic
- [x] Build update model with foreign key to topics model - topic(FK), title, content, update_image, published_on, updated_on, status
- [x] Migrate DB
- [x] Create topics model - new-features, fixes, site-news
- [x] Create update model objects - 3 test updates

**Acceptance Criteria:**
- [x] Admin can add updates
- [x] Admin can delete updates
- [x] Admin can update updates

**Unit Testing:**
- [x] UpdateCatagory Model
- [x] Update Model
