### ISSUE TITLE
USER STORY: User view site updates

### ISSUE THREAD

**Issue by Joe-Collins-1986** [Joe-Collins-1986/travel-app#9]
As a **user** I can **check site updates** so that **I understand site changes and improvements**.

**Comment by Joe-Collins-1986** [comment]
**Tasks:**
- [x] Post 3 updates to the home screen - also needs to be passed to login, register urls as ctx
- [x] Link to all updates - Use ListView
- [x] Add link to menu for small screens

**Acceptance Criteria:**
- [x] Users will be able to see the latest 3 updates on their home page for large screens
- [x] Users will have a link to all updates under the 3 updates on large screen
- [x] Users will have a link to all updates via the menu on small screens

**Unit Testing:**
- [x] admin updates url
- [x] admin updates list view
